apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: go-http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-deployment
spec:
  selector:
    matchLabels:
      app: go-http
  replicas: 1
  template:
    metadata:
      labels:
        app: go-http
    spec:
      nodeSelector:
        k8s.aliyun.com/vnode: "true"
      tolerations:
      - key: k8s.aliyun.com/vnode
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      containers:
      - name: go
        image: registry-vpc.cn-hangzhou.aliyuncs.com/dunfeng/argo-test:v0.0.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 8080
